import { StyleSheet, Dimensions } from "react-native";

const styleCodeConfirm = StyleSheet.create({
  container: {
    backgroundColor: "#2B85A2",
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 32,
    paddingVertical: '2%',
    paddingHorizontal: 16,
  },
  box: {
    alignItems: "center",
    justifyContent: "center",
    width: '100%',
  },
  containerBrandImage: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
  },
  brandImage: {
    width: 100,
    height: 100,
    resizeMode: 'contain',
  },
  contentHeaderMessage: {
    display: "flex",
    gap: 16,
    width: '100%',
    justifyContent: "flex-start",
    paddingVertical: '10%',
  },
  headerTitleWelcome: {
    color: '#EBC95D',
    fontFamily: 'Ubuntu_500Medium',
    fontSize: 26,
    lineHeight: 24,
    letterSpacing: 0.5,
  },
  headerTitleWelcomeSub: {
    color: '#F0E3C9',
    fontFamily: 'Ubuntu_300Light',
    fontSize: 18,
    lineHeight: 24,
    letterSpacing: 0.5,
  },
  content: {
    width: '100%',
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 56,
  },
  codeContent: {
    width: '100%',
    display: 'flex',
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    gap: 56,
  },
  boxCode: {
    width: "100%",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    gap: 16,
  },
  textLabel: {
    alignSelf: "stretch",
    color: "#FFF",
    fontFamily: "Ubuntu_500Medium",
    marginBottom: 8,
    fontSize: 16,
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: 16,
    letterSpacing: 0.5,
  },
  code: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    width: '100%',
    gap: 12,
  },
  input: {
    display: "flex",
    color: "#000000",
    textAlign: 'center',
    justifyContent: 'center',
    fontFamily: "Ubuntu_300Light",
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: 0.5,
    borderRadius: 8,
  },
  containerLink: {
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  labelLink: {
    color: "#0B2C37",
    textAlign: "center",
    alignSelf: "center",
    fontFamily: "Ubuntu_700Bold",
    fontSize: 12,
    lineHeight: 12,
    letterSpacing: 0.5,
  },
  button: {
    backgroundColor: "#EBC95D",
    display: "flex",
    width: 90,
  },
  labelButton: {
    fontFamily: "Ubuntu_500Medium",
  },

});
export default styleCodeConfirm;
