import { StyleSheet } from "react-native";

const styleSignUp = StyleSheet.create({
  container: {
    backgroundColor: "#2B85A2",
    flex: 1,
    gap: 16,
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: '10%',
  },
  content: {
    width: '100%',
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
  },
  contentHeaderMessage: {
    display: "flex",
    gap: 16,
    width: '100%',
    justifyContent: "flex-start",
    marginBottom: 16,
  },
  headerTitleWelcome: {
    color: '#EBC95D',
    fontFamily: 'Ubuntu_500Medium',
    fontSize: 26,
    lineHeight: 24,
    letterSpacing: 0.5,
  },
  headerTitleWelcomeSub: {
    color: '#F0E3C9',
    fontFamily: 'Ubuntu_300Light',
    fontSize: 18,
    lineHeight: 24,
    letterSpacing: 0.5,
  },
  scrollview: {
    width: '100%',
  },
  formContent: {
    width: '100%',
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    gap: 56,
  },
  form: {
    width: "100%",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    gap: 16,
  },
  input: {
    backgroundColor: "#fff",
    fontFamily: 'Ubuntu_300Light',
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: 0.5,
  },
  iconInputLeft: {
    color: '#323232',
    marginLeft: 12,
    marginRight: 12,
    fontSize: 20,
  },
  iconInputRight: {
    fontSize: 20,
    color: '#323232',
    marginLeft: 12,
    marginRight: 12,
  },
  textLabel: {
    color: "#FFF",
    alignSelf: 'stretch',
    fontFamily: 'Ubuntu_500Medium',
    marginBottom: 8,
    fontSize: 16,
    lineHeight: 16,
    letterSpacing: 0.5,
  },
  labelInput: {
    color: "#FFF",
    fontFamily: 'Ubuntu_500Medium',
    fontSize: 16,
    fontWeight: 300,
    lineHeight: 16,
    letterSpacing: 0.5,
    alignSelf: "stretch",
  },
  contentClickSignIn: {
    color: "#0B2C37",
    alignSelf: 'flex-start',
    fontFamily: 'Ubuntu_700Bold',
    textAlignVertical: 'center',
    fontSize: 12,
    lineHeight: 12,
    letterSpacing: 0.5,
  },
  labelClickSignIn: {
    display: 'flex',
    color: '#0B2C37',
    fontSize: 12,
    fontFamily: 'Ubuntu_700Bold',
    fontWeight: 400,
    letterSpacing: 0.5,
  },
  button: {
    backgroundColor: '#EBC95D',
    display: 'flex',
    width: 90,
    margin: 5,
  },
  textButton: {
    fontSize: 14,
    color: '#0B2C37',
    fontFamily: 'Ubuntu_500Medium',
  },
});

export default styleSignUp;