import { StyleSheet } from "react-native";

const styleSignUp = StyleSheet.create({
  container: {
    backgroundColor: "#2B85A2",
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 16,
    borderWidth: 1,
    borderColor: 'red',
  },
  content: {
    flexDirection: "column",
    justifyContent: "center",
    width: '100%',
    flex: 1,
    backgroundColor: "#2B85A2",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: '#EBC95D',
  },
  contentHeaderMessage: {
    display: "flex",
    gap: 16,
    width: '100%',
    justifyContent: "flex-start",
  },
  headerTitleWelcome: {
    color: '#EBC95D',
    fontFamily: 'Ubuntu_500Medium',
    fontSize: 26,
    lineHeight: 24,
    letterSpacing: 0.5,
  },
  headerTitleWelcomeSub: {
    color: '#F0E3C9',
    fontFamily: 'Ubuntu_300Light',
    fontSize: 18,
    lineHeight: 24,
    letterSpacing: 0.5,
  },

  formContent: {
    width: '100%',
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    gap: 56,
  },
  form: {
    width: "100%",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    gap: 16,
  },
  input: {
    backgroundColor: "#fff",
    fontFamily: 'Ubuntu_300Light',
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: 0.5,
  },
  textLabel: {
    color: "#FFF",
    alignSelf: 'stretch',
    fontFamily: 'Ubuntu_500Medium',
    marginBottom: 8,
    fontSize: 16,
    lineHeight: 16,
    letterSpacing: 0.5,
  },
  labelInput: {
    color: "#FFF",
    fontFamily: 'Ubuntu_500Medium',
    fontSize: 16,
    fontWeight: 300,
    lineHeight: 16,
    letterSpacing: 0.5,
    alignSelf: "stretch",
  },
  linkSignIn: {
    width: 'auto',
    display: 'flex',
    color: '#0B2C37',
    fontSize: 12,
    fontFamily: 'Ubuntu_700Bold',
    fontWeight: 400,
    letterSpacing: 0.5,
    alignSelf: "stretch",
    borderWidth: 1,
  },
  button: {
    backgroundColor: '#EBC95D',
    display: 'flex',
    width: 90,
    margin: 56,
    marginLeft: 138,
  },
  textButton: {
    fontSize: 14,
    color: '#0B2C37',
    fontFamily: 'Ubuntu_500Medium',
  },
  iconEye: {
    position: "absolute",
    top: 375,
    left: 320,
    width: "100%",
    height: "100%",
  },

});

export default styleSignUp;
