import { StyleSheet } from "react-native";
import {Dimensions} from 'react-native';

const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;


const styleRecoveryPassword = StyleSheet.create({
  contarinerP:{
      flex:1,
      width:windowWidth,
      height:windowHeight, 
      backgroundColor:"#2B85A2",
      alignItems:"center",
      justifyContent:"center",
    },
  container: {
      alignItems: 'center',
      gap: 9,
      marginRight:16,
      marginLeft:16,
    },
  input: {
      textAlign:"left",
      maxWidth:248,
      maxHeight:48,
      fontFamily: "Ubuntu",
      fontSize: 16,
      fontStyle: "normal",
      lineHeight: 24,
      letterSpacing: 0.5,
      borderRadius:8,
      marginLeft:16,
      marginRight:16,
      },
  linkSignIn: {
      marginTop:12,
      fontFamily: "Ubuntu",
      fontSize: 14,
      fontStyle: "normal",
      fontWeight: 400,
      letterSpacing: 0.5,
      alignSelf: "stretch",
      marginLeft:16,  
      },
  boxBotao:{
      alignContent:'center',
      marginTop: 56,
      width: 70,
      height:36,    
      },
  boxTexts:{
      maxWidth:328,
      marginBottom:56,
      marginRight:16,
      marginLeft:16,
      marginTop:64,
      },
  button: {
      borderRadius:4,
      padding:16,
      alignItems:'center',
      justifyContent:'center',
      backgroundColor:'#EBC95D',
      width: 89,
      height:36, 
      },
  textBotao:{
      alignItems:'center',
      height:36,
      color:'#0B2C37',
      textAlign: 'center',
      fontFamily: 'Ubuntu_500Medium',
      fontSize: 14,
      fontStyle: 'normal',
      fontWeight: 500,
      lineHeight: 36,
      letterSpacing: 1.25,
      },
  titleInput:{
      alignSelf: 'stretch',
      color: '#FFF',
      fontFamily: 'Ubuntu_500Medium',
      fontSize: 16,
      fontStyle: 'normal',
      fontWeight: 500,
      lineHeight: 16,
      letterSpacing: 0.5, 
      },
  textPrincipal:{
      color:'#F3B852',
      textAlign: 'center',
      fontFamily: 'Ubuntu_500Medium',
      fontSize: 26,
      fontStyle: 'normal',
      fontWeight: 500,
      lineHeight: 24,
      letterSpacing: 0.5,
      marginBottom:12,
      alignSelf: 'flex-start',
      },
  textSecundario:{
      color:'#F0E3C9',
      textAlign: 'center',
      fontFamily: 'Ubuntu_300Light',
      fontSize: 18,
      fontStyle: 'normal',
      fontWeight: 300,
      lineHeight: 24,
      letterSpacing: 0.5,
      marginBottom:12,
      alignSelf: 'flex-start',  
      },
});
export default styleRecoveryPassword;